name: Build Go Code

on:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Build
      run: mage

    - name: Test
      run: mage Test

