name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Build
      run: mage

    - name: Test
      run: mage Test

    - name: GitHub Tag
      uses: SOLIDSoftworks/semver-tags@latest
      with:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN}}
        tag-prefix: 'v'
        default-version: '0.0.1'
        prerelease: 'alpha'
