name: Tag Version

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    uses: ./.github/workflows/build.yml

  tag:
    runs-on: ubuntu-latest
    needs: build

    steps:     

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        release_branches: main